# Generated by Django 5.0 on 2025-12-07 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('drugbank', 'DrugBank'), ('alphafold', 'AlphaFold'), ('pubchem', 'PubChem'), ('rcsb_pdb', 'RCSB PDB'), ('firebase', 'Firebase FCM')], db_index=True, help_text='외부 API 서비스 이름', max_length=50)),
                ('endpoint', models.CharField(help_text='호출한 API 엔드포인트', max_length=500)),
                ('method', models.CharField(default='GET', help_text='HTTP 메소드', max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP 응답 상태 코드', null=True)),
                ('response_time_ms', models.IntegerField(help_text='응답 시간 (밀리초)', null=True)),
                ('cached', models.BooleanField(default=False, help_text='캐시에서 반환됨')),
                ('error_message', models.TextField(blank=True, help_text='에러 메시지 (실패 시)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='API 호출 시각')),
                ('user', models.ForeignKey(blank=True, help_text='API를 호출한 사용자 (내부 서비스 호출 시 null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API 사용 로그',
                'verbose_name_plural': 'API 사용 로그',
                'db_table': 'api_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', '-created_at'], name='api_usage_l_service_88a618_idx'), models.Index(fields=['user', '-created_at'], name='api_usage_l_user_id_683141_idx'), models.Index(fields=['status_code', '-created_at'], name='api_usage_l_status__af1554_idx')],
            },
        ),
    ]
