# Generated by Django 5.0 on 2025-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_patient_medical_record_number_patient_ssn_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(blank=True, help_text='외국인 환자 식별용', max_length=20, null=True, verbose_name='여권번호'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
    ]
