# Generated by Django 5.0 on 2025-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InferenceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(
                        db_index=True,
                        help_text="추론을 요청한 의사의 이름",
                        max_length=100,
                        verbose_name="담당 의사 이름",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        db_index=True,
                        help_text="추론 대상 환자의 이름",
                        max_length=100,
                        verbose_name="환자 이름",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        help_text="Flask ML 서버로 전송한 추론 요청 데이터 (전체 Payload)",
                        verbose_name="입력 데이터",
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        help_text="Flask ML 서버로부터 받은 추론 결과 데이터",
                        verbose_name="출력 데이터",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="추론 기록이 생성된 시간",
                        verbose_name="생성 일시",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML 추론 로그",
                "verbose_name_plural": "ML 추론 로그",
                "db_table": "ml_inference_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["doctor_name", "patient_name"],
                        name="ml_inferenc_doctor__8acd9f_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="ml_inferenc_created_d42201_idx"
                    ),
                ],
            },
        ),
    ]
