# Generated by Django 5.0.2 on 2025-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', help_text='관리자 승인 상태 (PENDING, APPROVED, REJECTED)', max_length=20, verbose_name='승인 상태'),
        ),
    ]
