# Generated by Django 5.0 on 2025-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_foreigner',
            field=models.BooleanField(default=False, verbose_name='외국인 여부'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, help_text='외국인 식별용', max_length=20, null=True, verbose_name='여권번호'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='연락처', max_length=20, null=True, verbose_name='전화번호'),
        ),
    ]
